#!/usr/bin/env bash
set -euo pipefail

RUN_TAG="${RUN_TAG:-step2lite_cf_adapter_directdisc_smoke_seed43}" \
DISTRIBUTION_REWARD_TYPE="${DISTRIBUTION_REWARD_TYPE:-cf_l1oo}" \
FEATURE_ADAPTER_ENABLE=1 \
FEATURE_ADAPTER_TYPE="${FEATURE_ADAPTER_TYPE:-residual_bottleneck}" \
FEATURE_ADAPTER_RANK="${FEATURE_ADAPTER_RANK:-64}" \
FEATURE_ADAPTER_DROPOUT="${FEATURE_ADAPTER_DROPOUT:-0.0}" \
CRITIC_LEARNING_RATE="${CRITIC_LEARNING_RATE:-0}" \
CRITIC_LR_HEAD="${CRITIC_LR_HEAD:-1e-5}" \
CRITIC_CLASSIFIER_LOSS_COEF="${CRITIC_CLASSIFIER_LOSS_COEF:-1.0}" \
CRITIC_DIRECT_DISCREPANCY_COEF="${CRITIC_DIRECT_DISCREPANCY_COEF:-0.01}" \
CRITIC_DIRECT_DISCREPANCY_TARGET="${CRITIC_DIRECT_DISCREPANCY_TARGET:-ema_gt}" \
EMA_BETA="${EMA_BETA:-0.99}" \
MAX_SAMPLES="${MAX_SAMPLES:-64}" \
NUM_EPISODES="${NUM_EPISODES:-1}" \
EVAL_MAX_SAMPLES="${EVAL_MAX_SAMPLES:-8}" \
EVAL_DOWN_MAX_SAMPLES="${EVAL_DOWN_MAX_SAMPLES:-8}" \
EVAL_BATCH_SIZE="${EVAL_BATCH_SIZE:-8}" \
EVAL_DOWN_BATCH_SIZE="${EVAL_DOWN_BATCH_SIZE:-8}" \
EVAL_GENERATE_MAX_LEN="${EVAL_GENERATE_MAX_LEN:-128}" \
EVAL_STEPS="${EVAL_STEPS:-10}" \
EVAL_DOWN_STEPS="${EVAL_DOWN_STEPS:-10}" \
ENABLE_GRADIENT_CHECKPOINTING="${ENABLE_GRADIENT_CHECKPOINTING:-1}" \
OPENRLHF_RAY_OBJECT_STORE_MEMORY_BYTES="${OPENRLHF_RAY_OBJECT_STORE_MEMORY_BYTES:-8589934592}" \
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; bash "${SCRIPT_DIR}/run_step1_paper_qa_feature_map.sh"
