#!/usr/bin/env bash
# ╔══════════════════════════════════════════════════════════════════╗
# ║  DSW post-restart bootstrap                                      ║
# ║                                                                   ║
# ║  Re-attach OSS-persisted credentials & venv into the ephemeral   ║
# ║  rootfs after a DSW container rebuild / image pull.              ║
# ║                                                                   ║
# ║  Run once after every DSW restart:                               ║
# ║      cd /mnt/data/ebft-distribution-new/code                     ║
# ║      bash scripts/dsw/bootstrap_after_restart.sh                 ║
# ║                                                                   ║
# ║  Idempotent: safe to re-run.                                     ║
# ╚══════════════════════════════════════════════════════════════════╝
#
# WHY THIS EXISTS
# ───────────────
# DSW (Alibaba PAI Data-Science-Workshop) backs the container by an
# overlay rootfs on /dev/vda. On image pull / "restart with new image"
# the WHOLE block device gets rebuilt — which means
#
#     /            (overlay rootfs, lower=image, upper=/dev/vda)   → wiped
#     /tmp         (ext4 on /dev/vda)                              → wiped
#     /mnt/workspace (ext4 on /dev/vda)                            → wiped
#     /home/admin/* (ext4 on /dev/vda)                             → wiped
#
# The ONLY layer that survives is the OSS-fuse mount:
#
#     /mnt/data    (ossfs2)                                        → persistent
#
# Therefore SSH keys, secrets, and the bootstrap script itself must
# either live on OSS or be checked into the git repo (which itself
# lives on OSS at /mnt/data/ebft-distribution-new/code).
#
# WHAT THIS SCRIPT DOES
# ─────────────────────
# 1. Copies the OSS-persisted GitHub SSH key into ~/.ssh and chmods 0600
#    (OSS-fuse cannot honor POSIX mode bits — OpenSSH would otherwise
#    refuse the key with "Permissions are too open").
# 2. Writes ~/.ssh/config so `git@github.com` tunnels through
#    ssh.github.com:443 (port 22 egress is often blocked) using the
#    just-copied identity.
# 3. Pre-trusts ssh.github.com:443 in known_hosts so the first push
#    doesn't prompt yes/no.
# 4. If a venv tarball is staged on OSS, extracts it to local ext4;
#    otherwise warns the user to run scripts/setup_env.sh.
# 5. Health-check: ssh -T git@github.com (informational; never fails).

set -euo pipefail

# ────────────────────────────────────────────────────────────────────
# Resolve paths from script location so this works regardless of CWD.
# ────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &>/dev/null && pwd )"
REPO_ROOT="${REPO_ROOT:-$( cd -- "${SCRIPT_DIR}/../.." &>/dev/null && pwd )}"
SECRETS_ROOT="${SECRETS_ROOT:-/mnt/data/dsw-secrets}"
KEY_SRC="${SECRETS_ROOT}/.ssh/id_ed25519_github"
PUB_SRC="${SECRETS_ROOT}/.ssh/id_ed25519_github.pub"
VENV_TARBALL_DIR="${VENV_TARBALL_DIR:-/mnt/data/dsw-secrets/venv-snapshots}"
VENV_LOCAL_ROOT="${VENV_LOCAL_ROOT:-/mnt/workspace/venvs}"

log()  { printf '[bootstrap] %s\n' "$*"; }
warn() { printf '[bootstrap][WARN] %s\n' "$*" >&2; }
die()  { printf '[bootstrap][ERROR] %s\n' "$*" >&2; exit 1; }

log "REPO_ROOT      = ${REPO_ROOT}"
log "SECRETS_ROOT   = ${SECRETS_ROOT}"
log "VENV_LOCAL_ROOT= ${VENV_LOCAL_ROOT}"

# ────────────────────────────────────────────────────────────────────
# 1) GitHub SSH identity → ~/.ssh (rootfs, ephemeral, but with strict
#    POSIX permissions so OpenSSH accepts the key).
# ────────────────────────────────────────────────────────────────────
mkdir -p "${HOME}/.ssh"
chmod 700 "${HOME}/.ssh"

if [[ ! -f "${KEY_SRC}" ]]; then
  warn "no GitHub key at ${KEY_SRC}"
  warn "git push over SSH will not work until you stage one there."
else
  cp -f "${KEY_SRC}" "${HOME}/.ssh/id_ed25519_github"
  chmod 600 "${HOME}/.ssh/id_ed25519_github"
  if [[ -f "${PUB_SRC}" ]]; then
    cp -f "${PUB_SRC}" "${HOME}/.ssh/id_ed25519_github.pub"
    chmod 644 "${HOME}/.ssh/id_ed25519_github.pub"
  fi
  log "copied GitHub key → ${HOME}/.ssh/ (mode 0600)"
fi

# ────────────────────────────────────────────────────────────────────
# 2) ~/.ssh/config: tunnel github.com through ssh.github.com:443.
# ────────────────────────────────────────────────────────────────────
cat > "${HOME}/.ssh/config" <<EOF
# Auto-generated by ${SCRIPT_DIR}/bootstrap_after_restart.sh
# Tunnel through ssh.github.com:443 to survive port-22 egress blocks.
Host github.com
    HostName ssh.github.com
    Port 443
    User git
    IdentityFile ${HOME}/.ssh/id_ed25519_github
    IdentitiesOnly yes
    StrictHostKeyChecking accept-new
    ServerAliveInterval 60
    ServerAliveCountMax 3
EOF
chmod 600 "${HOME}/.ssh/config"
log "wrote ${HOME}/.ssh/config"

# ────────────────────────────────────────────────────────────────────
# 3) Pre-trust ssh.github.com:443 to avoid first-push yes/no prompt.
# ────────────────────────────────────────────────────────────────────
touch "${HOME}/.ssh/known_hosts"
chmod 600 "${HOME}/.ssh/known_hosts"
if ! ssh-keygen -F "[ssh.github.com]:443" >/dev/null 2>&1; then
  ssh-keyscan -p 443 ssh.github.com 2>/dev/null >> "${HOME}/.ssh/known_hosts" || true
  log "added [ssh.github.com]:443 host keys to known_hosts"
fi

# ────────────────────────────────────────────────────────────────────
# 4) Optional venv recovery from OSS-staged tarball.
#    If you ever snapshot a working venv with:
#        tar --zstd -cf /mnt/data/dsw-secrets/venv-snapshots/venv.tar.zst \
#            -C /mnt/workspace/venvs .venv
#    this block will auto-extract on next boot.
# ────────────────────────────────────────────────────────────────────
mkdir -p "${VENV_LOCAL_ROOT}"

extract_venv() {
  local name="$1"
  local tarball
  for tarball in \
      "${VENV_TARBALL_DIR}/${name}.tar.zst" \
      "${VENV_TARBALL_DIR}/${name}.tar.gz"  \
      "${VENV_TARBALL_DIR}/${name}.tar"
  do
    [[ -f "${tarball}" ]] || continue
    if [[ -d "${VENV_LOCAL_ROOT}/${name}" ]]; then
      log "venv ${name} already on local ext4, skip extract"
      return 0
    fi
    log "extracting ${tarball} → ${VENV_LOCAL_ROOT}/"
    case "${tarball}" in
      *.zst) tar --zstd -xf "${tarball}" -C "${VENV_LOCAL_ROOT}" ;;
      *.gz)  tar -xzf      "${tarball}" -C "${VENV_LOCAL_ROOT}" ;;
      *)     tar -xf       "${tarball}" -C "${VENV_LOCAL_ROOT}" ;;
    esac
    log "extracted ${name}"
    return 0
  done
  return 1
}

for v in .venv .teacherVenv; do
  if [[ -d "${VENV_LOCAL_ROOT}/${v}" ]]; then
    log "venv ${v} present on local ext4"
  elif extract_venv "${v}"; then
    :
  else
    warn "venv ${v} not present and no tarball staged in ${VENV_TARBALL_DIR}"
    warn "  → run: bash ${REPO_ROOT}/scripts/setup_env.sh   (then re-run this bootstrap to symlink)"
    continue
  fi
  ln -sfn "${VENV_LOCAL_ROOT}/${v}" "${REPO_ROOT}/${v}"
  log "linked ${v}: ${REPO_ROOT}/${v} → ${VENV_LOCAL_ROOT}/${v}"
done

# ────────────────────────────────────────────────────────────────────
# 5) Health check (informational; never fails the script).
#    Expected output: 'Hi <user>! You've successfully authenticated...'
# ────────────────────────────────────────────────────────────────────
log "self-test: ssh -T git@github.com"
( ssh -T -o BatchMode=yes -o ConnectTimeout=8 git@github.com 2>&1 || true ) | head -3

log "done. cd ${REPO_ROOT} && git pull / push should work now."
